"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var caballero_1 = require("./caballero");
var elfo_1 = require("./elfo");
var mago_1 = require("./mago");
var vairoletto = new caballero_1.Caballero("Vairoletto", 1, 80, 20, 5);
var thakoles = new elfo_1.Elfo("Thakoles", 1, 60, 35, 10);
var azras = new mago_1.Mago("Azras", 1, 40, 45, 20);
console.log(vairoletto.obtenerInformacion());
console.log(thakoles.obtenerInformacion());
console.log(azras.obtenerInformacion());
vairoletto.atacar();
vairoletto.defender(12);
vairoletto.subirNivel();
thakoles.atacar();
thakoles.defender(12);
thakoles.subirNivel();
azras.atacar();
azras.defender(12);
azras.subirNivel();
